---
apiVersion: v1
kind: Service
metadata:
  name: my-external-service
spec:
  type: ClusterIP
#  selector:                 # don't include selector section
#    app: myapp
  ports:
  - port: 443
    targetPort: 443
