---
apiVersion: v1
kind: Service
metadata:
  name: svc-clusterip-httpd   # this is the service endpoint that has a dns entry that we can curl for. 
spec:
  type: ClusterIP
  ports:
    - port: 80          # you can choose to use a different port number here if you like.
      targetPort: 80
  selector:
    component: httpd_webserver