---
apiVersion: v1
kind: Pod
metadata:
  name: pod-demo      # both container's hostname will be set to this
  labels:
    component: centos
spec:
  containers:
    - name: cntr-httpd
      image: httpd:latest
      ports:
        - containerPort: 80
    - name: cntr-centos
      image: centos
      command: ["/bin/bash", "-c"]
      args:
        - |
          while true ; do
            date
            curl http://localhost
            sleep 10 
          done
