---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd_webserver
  template:
    metadata:
      labels:
        app: httpd_webserver
    spec: 
      containers:
        - name: cntr-httpd
          image: httpd:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          command: ["/bin/bash", "-c"]
          args:
            - |
              while true ; do
                date 
                sleep 10 
              done
          ports:
            - containerPort: 80