---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-httpd
  labels:
    component: httpd_webserver
spec:
  replicas: 2 
  selector:
    matchLabels:
      component: httpd_webserver
  template:
    metadata:
      labels:
        component: httpd_webserver
    spec: 
      containers:
        - name: cntr-nginx
          image: httpd:latest
          ports:
            - containerPort: 80