---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-provider
  labels:
    component: nginx_webserver
spec: 
  containers:
    - name: cntr-nginx
      image: nginx
      ports:
        - containerPort: 80