---
apiVersion: v1
kind: Pod
metadata:
  name: pod-centos
  labels:
    component: apache_webserver
spec: 
  containers:
    - name: cntr-centos
      image: centos
      env: 
        - name: FruitName
          valueFrom:               # this syntax is similar to how
            configMapKeyRef:       # we injected secrets into containers
              name: fav-fruit
              key: fruit.name
        - name: FruitColor
          valueFrom:
            configMapKeyRef:
              name: fav-fruit
              key: fruit.name
      command: ["/bin/bash", "-c"]
      args:
        - while true ; do
            date ;
            curl -s http://svc-clusterip-httpd.default.svc.cluster.local:4000 ;
            sleep 10 ;
          done