---
# apiVersion: v1   # had to comment this out for now because of https://github.com/kubernetes/kubernetes/issues/74597
kind: PersistentVolumeClaim 
metadata:
  name: pvc-db
spec:
  accessModes:
    - ReadWriteOnce   # this means that corresponding PV can only be used by a single node. Also see: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  resources:
    requests:
      storage: 100Mi
    # storaegeClassName: # Here you can make refrence to a storageclass object, kubernetes comes with a default
                         # storage class called 'standard'. This get's used if this line isn't used. If you want to use
                         # something else, e.g. nfs, then first create a NFS based storage object. For more info, see:
                         # https://kubernetes.io/docs/concepts/storage/storage-classes/#the-storageclass-resource