---
apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport-2nd-mysql-db-server
spec:
  type: NodePort
  ports:
    - port: 3050     # only used for pod-2-pod communication. 
      targetPort: 3306
      nodePort: 32306
  selector:
    component: 2nd-mysql_db_server