---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: pvc-mysql-db
spec:
  accessModes:
    - ReadWriteOnce   # this means that corresponding PV can only be used by a single node. Also see: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard  # This specifies which the StorageClass's name. It defaults to 'standard' if you omit this line