---
apiVersion: v1
kind: Pod
metadata:
  name: pod-centos
spec: 
  volumes:
    - name: shellscripts
      configMap:              # this is special volume which stores content of configmaps.
        name: customscripts
        defaultMode: 0744     # this is to make shell scrips executable
  containers:
    - name: cntr-centos
      image: centos
      volumeMounts:
        - name: shellscripts
          mountPath: /scripts       # this ends up creating the folder. 
      command: ["/scripts/healthcheck.sh"]  # here, we're running one of the scripts that we injected in. 