---
apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: pod-presets-httpd
spec:
  selector: 
    matchLabels:
      component: httpd
  env:
    - name: var1
      value: hello
    - name: var2
      value: world!!!
  volumes:
    - name: logs
      emptyDir: {}
  volumeMounts:
    - name: logs
      mountPath: /tmp/logs