---
apiVersion: v1
kind: Pod
metadata:
  name: pod-httpd-consumer
  labels:
    component: apache_webserver_consumer
spec: 
  containers:
    - name: cntr-centos
      image: centos
      command: ["/bin/bash", "-c"]
      args:
        - while true ; do
            date ;
            curl -s http://svc-clusterip-httpd.default.svc.cluster.local:4000 ;
            sleep 10 ;
          done