---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-httpd
  labels:
    component: httpd_webserver
spec:
  serviceName: httpd-service
  replicas: 2 
  selector:
    matchLabels:
      component: httpd_webserver
  template:
    metadata:
      labels:
        component: httpd_webserver
    spec: 
      containers:
        - name: cntr-httpd
          image: httpd:2.4.37
#          image: httpd:2.4.38
          ports:
            - containerPort: 80