---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-httpd
  labels:
    app: httpd_webserver
spec:
  serviceName: httpd-service     # Need to add this in stateful sets
  replicas: 2 
  selector:
    matchLabels:
      component: httpd_webserver
  template:
    metadata:
      labels:
        component: httpd_webserver
    spec:
      volumes: 
        - name: httpd-data-storage 
          persistentVolumeClaim:       
            claimName: pvc-httpd
      containers:
        - name: cntr-httpd
          image: httpd:2.4.37
          volumeMounts:
            - name: httpd-data-storage
              mountPath: /usr/local/apache2/htdocs/
          ports:
            - containerPort: 80