apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-webserver
spec:
  type: NodePort
  ports:
    - port: 3050
      targetPort: 80
      nodePort: 31000
  selector:
    component: nginx_webserver